-- 0054: Seed the IAM 2.0 employee role catalog used by staff management.
-- This is additive and intentionally does not touch Volunteer 2.0 tables.

INSERT IGNORE INTO permissions(permission_key, permission_name, sensitive_level, created_at)
VALUES
    ('org:read', '查看组织', 'INTERNAL', UTC_TIMESTAMP()),
    ('org:manage', '维护组织', 'SENSITIVE', UTC_TIMESTAMP()),
    ('plans:read', '查看年度MP', 'INTERNAL', UTC_TIMESTAMP()),
    ('plans:period_write', '维护本区域年度MP', 'SENSITIVE', UTC_TIMESTAMP()),
    ('members:read', '查看学长', 'INTERNAL', UTC_TIMESTAMP()),
    ('members:manage', '维护学长主数据', 'SENSITIVE', UTC_TIMESTAMP()),
    ('members:detail_view', '查看学长基本资料(脱敏)', 'INTERNAL', UTC_TIMESTAMP()),
    ('followups:manage', '管理关怀任务', 'SENSITIVE', UTC_TIMESTAMP()),
    ('renewals:read', '查看续费运营', 'INTERNAL', UTC_TIMESTAMP()),
    ('renewals:manage', '管理续费周期与导入', 'SENSITIVE', UTC_TIMESTAMP()),
    ('exports:normal', '普通脱敏导出', 'INTERNAL', UTC_TIMESTAMP()),
    ('attendance:sync', '同步签到出勤数据', 'SENSITIVE', UTC_TIMESTAMP()),
    ('attendance:adjudicate', '出勤裁定', 'SENSITIVE', UTC_TIMESTAMP()),
    ('enrollment:read', '查看新学长入塾申请', 'INTERNAL', UTC_TIMESTAMP()),
    ('enrollment:review', '审核新学长入塾申请', 'SENSITIVE', UTC_TIMESTAMP()),
    ('enrollment:payment_confirm', '确认入塾申请收款', 'SENSITIVE', UTC_TIMESTAMP()),
    ('enrollment:enroll', '将已完成申请正式入塾', 'SENSITIVE', UTC_TIMESTAMP()),
    ('enrollment:manage_link', '管理公开入塾申请二维码', 'SENSITIVE', UTC_TIMESTAMP());

INSERT INTO roles(role_key, role_name, is_system, is_active, created_at, updated_at)
VALUES
    ('employee_operations_lead', '运营中心负责人', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_operations_management', '运营管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_member_management', '学员管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_learning_management', '学习践行管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_development_management', '发展建设管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_renewal_management', '续费管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_finance_management', '财务管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_data_management', '数据管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('employee_administration_management', '行政管理', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
    ('read_only', '只读观察员', 1, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE
    role_name=VALUES(role_name),
    is_system=1,
    is_active=1,
    updated_at=VALUES(updated_at);

INSERT IGNORE INTO role_permissions(role_key, permission_key)
VALUES
    ('employee_operations_lead', 'org:read'),
    ('employee_operations_lead', 'org:manage'),
    ('employee_operations_lead', 'plans:read'),
    ('employee_operations_lead', 'plans:period_write'),
    ('employee_operations_lead', 'members:read'),
    ('employee_operations_lead', 'members:manage'),
    ('employee_operations_lead', 'members:detail_view'),
    ('employee_operations_lead', 'followups:manage'),
    ('employee_operations_lead', 'renewals:read'),
    ('employee_operations_lead', 'renewals:manage'),
    ('employee_operations_lead', 'exports:normal'),
    ('employee_operations_lead', 'attendance:sync'),
    ('employee_operations_lead', 'attendance:adjudicate'),
    ('employee_operations_lead', 'enrollment:read'),
    ('employee_operations_lead', 'enrollment:review'),
    ('employee_operations_lead', 'enrollment:payment_confirm'),
    ('employee_operations_lead', 'enrollment:enroll'),
    ('employee_operations_lead', 'enrollment:manage_link'),
    ('employee_operations_management', 'org:read'),
    ('employee_operations_management', 'plans:read'),
    ('employee_operations_management', 'plans:period_write'),
    ('employee_operations_management', 'members:read'),
    ('employee_operations_management', 'members:detail_view'),
    ('employee_operations_management', 'followups:manage'),
    ('employee_operations_management', 'renewals:read'),
    ('employee_member_management', 'org:read'),
    ('employee_member_management', 'members:read'),
    ('employee_member_management', 'members:manage'),
    ('employee_member_management', 'members:detail_view'),
    ('employee_member_management', 'followups:manage'),
    ('employee_member_management', 'exports:normal'),
    ('employee_learning_management', 'org:read'),
    ('employee_learning_management', 'plans:read'),
    ('employee_learning_management', 'members:read'),
    ('employee_learning_management', 'members:detail_view'),
    ('employee_learning_management', 'attendance:adjudicate'),
    ('employee_development_management', 'org:read'),
    ('employee_development_management', 'members:read'),
    ('employee_development_management', 'members:manage'),
    ('employee_development_management', 'members:detail_view'),
    ('employee_development_management', 'followups:manage'),
    ('employee_development_management', 'enrollment:read'),
    ('employee_development_management', 'enrollment:review'),
    ('employee_development_management', 'enrollment:enroll'),
    ('employee_renewal_management', 'org:read'),
    ('employee_renewal_management', 'members:read'),
    ('employee_renewal_management', 'members:detail_view'),
    ('employee_renewal_management', 'renewals:read'),
    ('employee_renewal_management', 'renewals:manage'),
    ('employee_finance_management', 'org:read'),
    ('employee_finance_management', 'renewals:read'),
    ('employee_finance_management', 'renewals:manage'),
    ('employee_finance_management', 'enrollment:read'),
    ('employee_finance_management', 'enrollment:payment_confirm'),
    ('employee_data_management', 'org:read'),
    ('employee_data_management', 'members:read'),
    ('employee_data_management', 'members:detail_view'),
    ('employee_data_management', 'exports:normal'),
    ('employee_administration_management', 'org:read'),
    ('employee_administration_management', 'members:read'),
    ('employee_administration_management', 'members:detail_view'),
    ('employee_administration_management', 'followups:manage'),
    ('read_only', 'org:read'),
    ('read_only', 'plans:read'),
    ('read_only', 'members:read'),
    ('read_only', 'renewals:read');
