PRAGMA foreign_keys=OFF;
CREATE TEMPORARY TABLE wuxi_org_rollback_guard (n INTEGER CHECK(n=0));
INSERT INTO wuxi_org_rollback_guard
SELECT
    (SELECT COUNT(*) FROM org_units WHERE parent_id IN ('org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin') AND id NOT IN ('org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM employee_authorization_grants WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM data_scope_grants WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM member_org_relations WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM employee_service_responsibilities WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM volunteer_appointments WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM members WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin') OR development_org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM followup_tasks WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM attendance_event_groups WHERE org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin') OR study_org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'))
  + (SELECT COUNT(*) FROM volunteer_service_units WHERE home_shuku_org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin') OR service_target_org_unit_id IN ('org-wuxi','org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin'));
DROP TABLE wuxi_org_rollback_guard;
DELETE FROM org_units
WHERE id IN ('org-wuxi-guidance-1','org-wuxi-guidance-2','org-wuxi-ling-hang-1','org-wuxi-ling-hang-2','org-wuxi-ling-hang-3','org-wuxi-zhi-cheng-1','org-wuxi-zhi-cheng-2','org-wuxi-xiong-ying-1','org-wuxi-xiong-ying-2','org-wuxi-xiong-ying-3','org-wuxi-ju-long-1','org-wuxi-ju-long-2','org-wuxi-xing-huo-1','org-wuxi-xing-huo-2','org-wuxi-xing-huo-3','org-wuxi-zhuo-yue-1','org-wuxi-zhuo-yue-2','org-wuxi-zhuo-yue-3','org-wuxi-jing-jin');
DELETE FROM schema_migrations WHERE version='0058_wuxi_org_master_data.sql';
PRAGMA foreign_keys=ON;
